import { makeStyles } from '@material-ui/core/styles';

export default makeStyles(() =>({
    container:{
        background:'#2C3E50',
        minHeight:'100vh',
        paddingTop:'5vh',
    },
    logo:{
        color:'#fff',
        textTransform:'uppercase',
        letterSpacing:'2px',
        fontWeight:'bold',
        textAlign:'center',
        padding:'2vh 0 10vh'
    },
    inputContainer:{
        minHeight:'50vh',
    },
    form:{
        width:'90%',
        margin:'auto'
    },
    input:{
        width:'100%',
        padding:'13px',
        background:'#C4C4C4',
        marginBottom:'10px',
        outline:'none',
        border:'none',
        textAlign:'center',
        fontSize:'16px',
        color:'black'
    },
    button:{
        background:'#B11E1E',
        marginBottom:'10px',
        color:'#fff',
        fontSize:'16px',
        fontWeight:'bold',
        cursor:'pointer'
    },
    orText:{
        textAlign:'center',
        marginBottom:'10px',
    },
    googleButton:{
        fontWeight:'bold',
        padding:'7px',
        marginBottom:'10px',
    },
    singUpSwitch:{
        width:'90%',
        height:'40px',
        margin:'auto'
    },
    singUpSwitchText:{
        color:'#fff',
        textDecoration:'underline',
        cursor:'pointer'
    }
}))